### ISSUE TITLE
crashes, adding new task deletes older one

### ISSUE THREAD

**Issue by js-d-coder** [lainsce/yishu#10]
Hello,
Thanks for this app.  
I have just tried latest version `1.0.5` of this app. It has two bugs for sure.  

* First it crashed when I click on Done button. It happened two times.
* Adding new task deletes older one.

These two bugs have made it pretty much hard to use.

**Comment by lainsce** [comment]
I don't seem to have hit this, have you done anything different with the files or changed things on the settings of Yishu?

**Comment by lainsce** [comment]
Due to inactivity, I'll close this.

**Comment by junaidiqbal1948** [comment]
I am having Same Problems.

**Comment by js-d-coder** [comment]
I am using all default settings, didn't made any changes since installation...

**Comment by junaidiqbal1948** [comment]
Same here. I installed chores now btw.

**Comment by lainsce** [comment]
Can you guys make a video of the bug happening so I can see when does it happen by what series of actions?

**Comment by junaidiqbal1948** [comment]
Yeah, Sure.

**Comment by lemilonkh** [comment]
Right after installing, I open Yishu and it tries to load `/home/USER` as its TODO directory, which fails.

If it is run from the command line, you get the following error messages:
```
[INFO 12:34:40.628892] Application.vala:154: Yishu version: (null)
[INFO 12:34:40.628944] Application.vala:156: Kernel version: 4.13.0-37-generic
Created new window in existing browser session.
[2745:2848:0317/123444.870168:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
[WARNING 12:34:56.786237] TodoFile.vala:68: Can't open directory
[WARNING 12:34:56.786530] TodoFile.vala:87: Error opening file '/home/USER': Is a directory
[WARNING 12:34:56.786561] Application.vala:344: Failed to write file
```

Is there a config file I can edit to manually set the path?

I can't select any files using the Custom location file picker (it only shows folders and I can't 'Open' them)  
Also the i Icon doesn't do anything for me

**Comment by lainsce** [comment]
If the custom file picker doesn't find any .todo.txt file it will show only folders. Create such a file in Home to start adding tasks.

**Comment by lainsce** [comment]
Closing this issue, if the issue persists, make a new one with an useful way for me to know what's wrong.
