### ISSUE TITLE
The app doesn't keep any list after closing

### ISSUE THREAD

**Issue by janxkoci** [lainsce/yishu#15]
I just installed this app from elementary AppCentrum and tried to use it, but whenever i create a task, it disappears after i restart the app. I also tried to search my drive for todo.txt file but found none (except one library in miniconda3).

Version: 1.0.5

**Comment by lainsce** [comment]
It should read a file in your Home folder called todo.txt before adding tasks, I'll see what i can do.

**Comment by janxkoci** [comment]
I have such file in my dropbox but I couldn't even set *that* as the custom location - the dialog just keeps opening folders but doesn't allow selection of anything else (but that's another bug).

Edit: I just copied the file from dropbox to my home and the app still doesn't see it.

![image](https://user-images.githubusercontent.com/19331850/40411929-24e1ec0c-5e72-11e8-806d-cf07ec2c54f1.png)

**Comment by lainsce** [comment]
Now that's a bug, I'll see what I can do 😄

**Comment by ghost** [comment]
Same issue here.

**Comment by lainsce** [comment]
Fixed in 1.0.6~
