### ISSUE TITLE
Cannot select custom location from the dialog

### ISSUE THREAD

**Issue by janxkoci** [lainsce/yishu#16]
The dialog to select custom location only shows folders. 

![snimek z 2018-05-23 10-17-40](https://user-images.githubusercontent.com/19331850/40412174-de9c72ca-5e72-11e8-9cc9-5b6a219ed8ac.png)

When i try to select one, it will just go inside it, until i reach the deepest folder. At this point the open button is grayed out.

![snimek z 2018-05-23 10-17-46](https://user-images.githubusercontent.com/19331850/40412189-e458e9f0-5e72-11e8-8211-10ebc15b7c7d.png)

**Comment by lainsce** [comment]
It's supposed to open a custom file in a custom location, not to set a location as the place for the new list. It might be confusing, I dunno. I did add an icon right beside the location picker explaining what it does, the ```(!)``` icon.

**Comment by lainsce** [comment]
Fixed in 1.0.6~
