### ISSUE TITLE
Crashes on trying to open my todo.txt file

### ISSUE THREAD

**Issue by esijg** [lainsce/yishu#18]
I installed the latest version of Yishu found on flathub (1.0.4), on Ubuntu 18.04.
When trying to open my todo.txt file the program crashes and I get the following error in the terminal.

```
[INFO 15:55:27.399595] Application.vala:154: Yishu version: (null)
[INFO 15:55:27.399621] Application.vala:156: Kernel version: 4.15.0-23-generic
[FATAL 15:55:44.450502] string_splice: assertion '_tmp12_' failed
[FATAL 15:55:44.450526] string_strip: assertion 'self != NULL' failed
```
This does not seem happen with a new empty todo list. I have not managed to isolate the problem further. My first thought was that this was related to non english letters in my todo.txt file but that seems not to have been the problem.

edit: not sure if connected but I've now managed to crash Yishu by creating and then trying to delete a task with non english letters. So there's def. something odd going on with non english letters.

**Comment by lainsce** [comment]
The thing is, it's purposefully not compatible with non-english letters due to how the todo.txt "API" is, with many clients out there also not supporting non-english letters. So I can't break compatibility for others and fix this bug. Also, try using the latest Yishu, from this repository.
