### ISSUE TITLE
Incorrectly writes project and context names with non english characters

### ISSUE THREAD

**Issue by esijg** [lainsce/yishu#19]
I installed the latest version of Yishu found on flathub (1.0.4), on Ubuntu 18.04.

If I create a new task and use non english (Icelandic) characters in project or context name, then when saved Yishu will somehow cut the project/context name right before the non english character. But insert the rest of the project/context name at the end of the task but before the project/context

![mynd](https://user-images.githubusercontent.com/2924543/42127042-5185d25a-7c81-11e8-9fdc-0bbc5beacff7.png)

todo.txt file in question attached
[todo.txt](https://github.com/lainsce/yishu/files/2151999/todo.txt)

**Comment by lainsce** [comment]
The thing is, it's purposefully not compatible with non-english letters due to how the todo.txt "API" is, with many clients out there also not supporting non-english letters. So I can't break compatibility for others and fix this bug.

**Comment by esijg** [comment]
Fair enough.

I do want to add though that of all the clients I've tested (todotxt-machine, go for it, qtodotxt, official todo.sh, todo.txt on android, simpletask on android, etc), Yishu is the only todotxt client I've used that seems to have this problem. QTodoTxt had a similar problem at one point but if I am not mistaken it was fixed.

**Comment by lainsce** [comment]
I'll try to see if I can save faux-versions of the non-english letters, ex. á -> a.
