### ISSUE TITLE
Change of default location doesn't stick.

### ISSUE THREAD

**Issue by martindahlswe** [lainsce/yishu#20]
When choosing "Dropbox Folder" as Default Location and closing and reopening the app the setting is not remembered and it goes back to ~.

I'm using version 1.0.7 from the Elementary AppCenter.

Thanks!

**Comment by lainsce** [comment]
1.0.7 is deprecated, with version 1.0.8 or cloning this repo, you'll get the fix for this bug.
I will however review the code to see if anything's missing.

**Comment by lainsce** [comment]
I see no problem in the code related to this, especially in the last version published.
