### ISSUE TITLE
How to get your app on other linux distributions than elementary OS?

### ISSUE THREAD

**Issue by kaefert** [lainsce/yishu#24]
Hi there!

I stumbled upon your applications here because http://todotxt.org/ lists https://burnsoftware.wordpress.com/daytasks/ which's author told the last user asking for a new feature a year ago to have a look at the newer todo.txt app "Yishu", so your app here.

I think DayTasks is quite nice, but beeing actively developed is also a very nice feature so I thought I'll have a look at Yishu.

Sadly I can't see how to easily install it on my Linux Mint 18.3 (based on Ubuntu 16.04). You have a link to "appcenter" from elementary OS, but I'm quite happy with my distribution and don't want to switch. Since elementary OS seems to be also based on Ubuntu, maybe you could publish your builds in a way that works for other Ubuntu based distributions too?

Is there maybe someway to get a deb package out of this "appcenter" release? When I click on it I only see a description of your app and a button to get elementary OS, no way to download the binary.

So let's try building it myself.
```
cd ~/git
git clone https://github.com/lainsce/yishu.git
cd yishu
sudo apt install meson
meson build
```

Which results in this error for me:

> The Meson build system
> Version: 0.40.1
> Source dir: /home/kaefert/git/yishu
> Build dir: /home/kaefert/git/yishu/build
> Build type: native build
> Project name: com.github.lainsce.yishu
> Native c compiler: cc (gcc 5.4.0)
> 
> Meson encountered an error in file meson.build, line 2, column 0:
> Could not execute Vala compiler "valac"

So let's install that and try again:
```
sudo apt install valac
meson build
```
which results in this error:

> The Meson build system
> Version: 0.40.1
> Source dir: /home/kaefert/git/yishu
> Build dir: /home/kaefert/git/yishu/build
> Build type: native build
> Project name: com.github.lainsce.yishu
> Native c compiler: cc (gcc 5.4.0)
> Native vala compiler: valac (valac 0.30.1)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Native dependency glib-2.0 found: YES 2.48.2
> WARNING: GLib compiled dependencies do not work reliably with 
> the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
> Configuring config.h using configuration
> 
> Meson encountered an error in file meson.build, line 43, column 0:
> Native dependency 'granite' not found

Looking for granite in my package manager I only find "granite-demo" and "gir1.2-granite-1.0" - neither of which sound like it would satisfy this dependency of your app. Sigh. This seems to be not too easy. Ah. Stupid of me. Found it.: "libgranite-dev"
```
sudo apt-get install libgranite-dev
meson build
```
> The Meson build system
> Version: 0.40.1
> Source dir: /home/kaefert/git/yishu
> Build dir: /home/kaefert/git/yishu/build
> Build type: native build
> Project name: com.github.lainsce.yishu
> Native c compiler: cc (gcc 5.4.0)
> Native vala compiler: valac (valac 0.30.1)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.29.1)
> Native dependency glib-2.0 found: YES 2.48.2
> WARNING: GLib compiled dependencies do not work reliably with 
> the current version of GLib. See the following upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=774368
> Configuring config.h using configuration
> Native dependency granite found: YES 0.3.0
> Native dependency gobject-2.0 found: YES 2.48.2
> Native dependency gtk+-3.0 found: YES 3.18.9
> Program meson/post_install.py found: YES (/usr/bin/env python3 /home/kaefert/git/yishu/meson/post_install.py)
> Build targets in project: 6

**Comment by kaefert** [comment]
So I'm currently at this state of a "build script":
```
cd ~/git
git clone https://github.com/lainsce/yishu.git
cd yishu
git checkout 1.0.9
sudo apt install meson valac libgranite-dev libgtk-3-dev
meson build
meson configure -Dprefix=/usr
cd build
ninja
```
Which gives me these errors:
```
[4/12] Compiling Vala source ../src/Application.vala ../src/Task.vala ../src...c/MainWindow.vala ../src/Preferences.vala ../src/Constants/AppSettings.vala.
FAILED: com.github.lainsce.yishu@exe/Application.c com.github.lainsce.yishu@exe/Task.c com.github.lainsce.yishu@exe/TaskDialog.c com.github.lainsce.yishu@exe/TodoFile.c com.github.lainsce.yishu@exe/MainWindow.c com.github.lainsce.yishu@exe/Preferences.c com.github.lainsce.yishu@exe/AppSettings.c 
valac '--debug' '-d' 'com.github.lainsce.yishu@exe' '-C' '--pkg' 'granite' '--pkg' 'gobject-2.0' '--pkg' 'gtk+-3.0' '--gresources=../data/style.gresource.xml' '/home/kaefert/git/yishu/vapi/config.vapi' '--vapidir=/home/kaefert/git/yishu/vapi/' ../src/Application.vala ../src/Task.vala ../src/TaskDialog.vala ../src/TodoFile.vala ../src/MainWindow.vala ../src/Preferences.vala ../src/Constants/AppSettings.vala
../src/Preferences.vala:38.30-38.48: error: The name `HeaderLabel' does not exist in the context of `Granite'
            var header = new Granite.HeaderLabel (_("Todo.txt Preferences"));
                             ^^^^^^^^^^^^^^^^^^^
../src/Preferences.vala:38.17-38.76: error: var declaration not allowed with non-typed initializer
            var header = new Granite.HeaderLabel (_("Todo.txt Preferences"));
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Preferences.vala:140.31-140.36: error: The name `header' does not exist in the context of `Yishu.Widgets.Preferences'
            main_grid.attach (header, 0, 1, 1, 1);
                              ^^^^^^
../src/TaskDialog.vala:43.25-43.43: error: The name `HeaderLabel' does not exist in the context of `Granite'
			var task_label = new Granite.HeaderLabel (_("Task"));
			                     ^^^^^^^^^^^^^^^^^^^
../src/TaskDialog.vala:43.8-43.55: error: var declaration not allowed with non-typed initializer
			var task_label = new Granite.HeaderLabel (_("Task"));
			    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/TaskDialog.vala:44.25-44.43: error: The name `HeaderLabel' does not exist in the context of `Granite'
			var prio_label = new Granite.HeaderLabel (_("Priority"));
			                     ^^^^^^^^^^^^^^^^^^^
../src/TaskDialog.vala:44.8-44.59: error: var declaration not allowed with non-typed initializer
			var prio_label = new Granite.HeaderLabel (_("Priority"));
			    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/TaskDialog.vala:98.22-98.31: error: The name `task_label' does not exist in the context of `Yishu.TaskDialog'
			main_grid.attach (task_label, 0, 0, 1, 1);
			                  ^^^^^^^^^^
../src/TaskDialog.vala:101.22-101.31: error: The name `prio_label' does not exist in the context of `Yishu.TaskDialog'
			main_grid.attach (prio_label, 0, 2, 1, 1);
			                  ^^^^^^^^^^
../src/Application.vala:381.29-381.41: error: Argument 1: Cannot pass ref argument to non-reference parameter
				tasks_list_store.remove(ref task.iter);
				                        ^^^^^^^^^^^^^
Compilation failed: 10 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.


^^^^^^^^^^^^
Compilation failed: 10 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by lainsce** [comment]
You'd need the latest `libgranite-dev` which should be at version 5 or higher, otherwise Yishu won't compile. My guess is Linux Mint repos only have it at version 4.

**Comment by kaefert** [comment]
Oh. okey. well I guess I'll stick with DayTasks for now then. Would be nice if you could do releases that work for more than just Elementary OS.

**Comment by lainsce** [comment]
Well, ask the Linux Mint packagers if they can update libgranite-dev, otherwise, just install it manually or something?

**Comment by kaefert** [comment]
Well, I guess it would probably be possible to get a more recent libgrante-dev somehow, but I think that would require more effort than I am willing to put into it right now. sorry. thanks for your reply.
