### ISSUE TITLE
Option to filter tasks

### ISSUE THREAD

**Issue by BharatKalluri** [lainsce/yishu#25]
Hi @lainsce ,

Love yishu. But after you pack all your todo in one file. It goes lengthy. An option to filter on projects/contexts would really help for understanding what is todo.

Thanks for your work!

**Comment by lainsce** [comment]
You mean a search bar? I'll see what I can do :smile:

**Comment by lainsce** [comment]
In progress:

- [x] Searchbar Widget
- [x] Search tasks
