### ISSUE TITLE
Tasks don't save until a location is manually chosen

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/yishu#27]
If I don't choose a location from Preferences, my tasks are not saved. Once I manually choose a location, old tasks that were located there show up, and any new ones I create are saved.

**Comment by cassidyjames** [comment]
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/611168/47303087-47df3080-d5e0-11e8-944e-e545b0cb157d.gif)

**Comment by lainsce** [comment]
I'm looking into this.

**Comment by lainsce** [comment]
Fixed in master.
