### ISSUE TITLE
Segmentation Fault (when creating task)

### ISSUE THREAD

**Issue by guilmour-asc** [lainsce/yishu#3]
Hey, what's up... Great work on your app, it's beautiful, well designed.

I'd like to inform an issue, though. Creating a task causes segmentation fault, as shown on the GIF screeenshot below:

![peek 26-11-2017 09-10](https://user-images.githubusercontent.com/26415345/33239487-d9dfd6e8-d289-11e7-8fe4-e31542dc56fa.gif)

Thanks for the attention.

**Comment by guilmour-asc** [comment]
If I make a "todo.txt" file, and open on Yishu, it functions good as expected. The issue, then, only occurs if you try to create a task without opening a todo.txt...
Look below, now that I opened a created blank file, I got success.

![captura de tela de 2017-11-26 11 34 35](https://user-images.githubusercontent.com/26415345/33240505-ddd21b1c-d29d-11e7-945d-06640a2a659d.png)

**Comment by lainsce** [comment]
Expect a fix in 1.0.2, I've fixed this behaviour while also adding some goodies for people that don't already have a todo.txt file.
