### ISSUE TITLE
Yishu crashes when opening file shared by Todo.txt Early Access app on Android

### ISSUE THREAD

**Issue by leggettc18** [lainsce/yishu#34]
Yishu crashes when I try to open my todo.txt File. It is stored in Dropbox (but in a custom location within that, Dropbox/Apps/Todo/todo.txt). The Todo.txt android app (currently in early access) is also using the same file, and the "Go For It!" app also opens it with no issues (although I don't want to use it because it doesn't have any extra formatting for the dates and such).  Here are the contents of my todo.txt file (just one line).

```
2019-02-01 Clean Bathroom due:2019-02-04
```

Any idea what could be going on here?

**Comment by leggettc18** [comment]
My mistake, should've probably added that I'm on elementary os juno, using the latest version available from the elementary os app store.

**Comment by lainsce** [comment]
Maybe the `due:date` part is tricking Yishu and crashing it... I'll see what I can do.

**Comment by lainsce** [comment]
Apparently, that `due:2019-02-04` part is out of spec and possibly an extension made on the todo.txt file by that app on Android, possibly hinting that it's a new thing no other client does. As such, for not breaking compatibility with all other clients, I'm not fixing this bug.

**Comment by bluebirch** [comment]
Sorry, I don't get it. The `due:date` tag is additional metadata, and yishu should ignore it, not crash?

**Comment by lainsce** [comment]
The problem is that if Yishu reads it, other clients won't so I'm breaking an universal API.
