### ISSUE TITLE
Some translations aren't working correctly

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/yishu#38]
I just updated the app, and there is some issues with some translations. I checked the translations strings but I wasn't able to find out where is the problem. Can you please check?

First of all, content of appdata.xml doesn't seems to be translated. But there is the issue with others apps, maybe it's due to AppCenter.

Else there is theses strings which aren't translated: "Search task" and "No Todo.txt File Open" and also "Home Folder" (and others strings in this list).

**Comment by NathanBnm** [comment]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/45366162/54183684-01ae3f00-44a5-11e9-8ad2-2b6c61c18b23.png)

**Comment by lainsce** [comment]
Will do a fix
