### ISSUE TITLE
Not enough contrast when task is selected

### ISSUE THREAD

**Issue by Allen-B1** [lainsce/yishu#41]
There isn't enough contrast between the blue background and the grey time text (when a task is elected). It's hard to see "Today".

v1.1.6

![Screenshot](https://user-images.githubusercontent.com/28495335/56623919-5399c700-6604-11e9-8b83-80cfd0619f9e.png)

**Comment by lainsce** [comment]
I'll see what I can do. :+1:

**Comment by lainsce** [comment]
Fixed.
