### ISSUE TITLE
App closes if you press supr twice.

### ISSUE THREAD

**Issue by Julioevm** [lainsce/yishu#42]
If you press supr twice, to delete two tasks, the app suddenly closes.

Thanks!

**Comment by lainsce** [comment]
What do you mean by `supr`? Do you mean Super key (windows symbol)? I'll look into it in August.

**Comment by Julioevm** [comment]
Sorry I was referring to the **Del** key, Supr on the spanish keyboard.

**Comment by lainsce** [comment]
Fixed
