### ISSUE TITLE
Notes and settings are not storing

### ISSUE THREAD

**Issue by HannanAkbar** [lainsce/yishu#43]
Installed Yishu via Flatpak. I gave the directory and todo.txt write permission but it's not loading any todos or storing anything. CLI works perfectly.

![Screen-recorder_Navigator_20190726160413](https://user-images.githubusercontent.com/5216873/61947648-32f45b00-afbf-11e9-8ef1-b9fb2153e4a7.gif)

**Comment by lainsce** [comment]
It may have to do with the sandboxing permissions, which I have zero knowledge of.
I'll try to fix it, but don't expect much since I'm a beginner at flatpaks.

**Comment by lainsce** [comment]
Can't help with this, ask for help on Flathub.
