### ISSUE TITLE
Crash on existing file open

### ISSUE THREAD

**Issue by maxlStone** [lainsce/yishu#48]
* Describe the issue
When I try to open my existing todo.txt file or if I move my existing file to the home directory so that the app can open it, the app crashes with this message shown in the terminal:
```
** (com.github.lainsce.yishu:10844): CRITICAL **: 15:52:52.374: string_splice: assertion '_tmp6_' failed

(com.github.lainsce.yishu:10844): GLib-CRITICAL **: 15:52:52.374: g_regex_match_full: assertion 'string != NULL' failed

** (com.github.lainsce.yishu:10844): CRITICAL **: 15:52:52.374: string_strip: assertion 'self != NULL' failed
[1]    10844 segmentation fault  /usr/bin/com.github.lainsce.yishu
```

I tried to remove all non-English characters, even though the terminal client and the android client display them correctly (ö,ä,ü in my case), but that did not help.

* State what version you're using
1.2.0 from the elementaryOS AppCenter

Thank you for the app!

**Comment by lainsce** [comment]
Does your file contain future dates?

**Comment by maxlStone** [comment]
Yes it contains due dates. The dates are all in the past.

I tested it without the due entries and the app started normally.

**Comment by lainsce** [comment]
No further bugs, so, closing…
