### ISSUE TITLE
Done tasks have wrong format

### ISSUE THREAD

**Issue by maxlStone** [lainsce/yishu#49]
* Describe the issue
Finishing a task just adds a `x ` at the beginning of the line without changing the format of the priority.
So the current format is:
`x (A) task`
The expected format of the priority of a finished task is `pri:<priority>` at the end of the line:
`x task pri:A`

* State what version you're using
1.2.0

Edit: [Todo.txt format](https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space)

**Comment by lainsce** [comment]
As per your link, doing `pri:A` is only for preserving metadata of the priority in case a client discards them. Since Yishu doesn't discard anything, it's not needed to make this change.

**Comment by maxlStone** [comment]
Oh, sorry. I overlooked that.

**Comment by maxlStone** [comment]
What is if other clients that a user uses discard the information about the priority? How should this app handle it, if the user wants to revive the task to undone?

**Comment by lainsce** [comment]
Simply edit the file beforehand and remove these extra metadata things.
