### ISSUE TITLE
Issues with todo.txt location on Linux

### ISSUE THREAD

**Issue by WebShapedBiz** [lainsce/yishu#5]
Hi.

On Elementary OS Loki, for backup/sync purposes, I'm trying to place my todo.txt in one of my home folders instead of the default location, in my home folder. Also, I defined this path in dconf as `com.github.lainsce.yishu.todo-txt-file-path` key.
Without any problems, Yishu manages to find this file on startup and display containing tasks.

Issues:
- If I add another task, the old task gets overwritten while Yishu creates a new todo.txt file in my home directory and places this new task there. From that point, after each run, Yishu is using only the new todo.txt file.
- However, if I only edit the old task, the updated task is written in the original todo.txt file and Yishu continues using it on every following run.

I would like to know Is there a way to have a custom todo.txt file path?

Thank you for your time and effort.

EDIT: When Yishu create a new file, it does not change the key value in dconf. The value remains to be the path to the original todo.txt and Yishu just ignores it.

**Comment by lainsce** [comment]
I was in the middle of defining ways of setting a custom place if needed before I released the stable version in AppCenter. It's in the works, but you're going to wait until I come back from my vacation (in January 4th) before I start implementing this.

**Comment by WebShapedBiz** [comment]
Thank you @lainsce for your reply.

**Comment by lainsce** [comment]
I guess this will need more than one release. I've now made use of the key in the new Preferences dialog now present in Yishu 1.0.3. Next, I will tackle this.

**Comment by WebShapedBiz** [comment]
Cheers.

**Comment by lainsce** [comment]
And I got it to be in 1.0.3, releasing soon! ❤️
