### ISSUE TITLE
Change requested for AppCenter: Saved Search non-functional

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/yishu#56]
Thanks for submitting your latest release (1.2.3) to AppCenter! However, while reviewing the release, we found an issue that needs to be resolved.

It appears the "saved search" functionality does not work as advertised. Please either fix this functionality or remove references to it to ensure your app does what it says. Once you've made the requested changes, create a new release on GitHub and re-submit it at the AppCenter Dashboard.

Thanks! As always, if you have any questions you can reply here.

**Comment by lainsce** [comment]
After testing it here, it does work, @cassidyjames :

1. Make three tasks: Each named AAA, BBB, CCC.
2. Search for BBB. Confirm BBB was selected.
3. Quit Yishu
4. Reopen, and BBB should still be selected.

**Comment by cassidyjames** [comment]
It's still pretty buggy with the 1.2.5 release. But I can see that it does sometimes work, so it won't block the release anymore.
