### ISSUE TITLE
Remember last open location

### ISSUE THREAD

**Issue by chrisbeardy** [lainsce/yishu#57]
Every time I open Yishu it defaults to the Home folder for looking for the todo.txt. even if Default location is set to Nextcloud or custom. 

It would be great if it remembered the last location and opened that file.

**Comment by lainsce** [comment]
This is fixed in the repo on master, I'm fixing another thing entirely and then will release a new update with this fixed. :D

**Comment by chrisbeardy** [comment]
Awesome 👍. Great job.
