### ISSUE TITLE
Completed date is not added on task completion

### ISSUE THREAD

**Issue by chrisbeardy** [lainsce/yishu#58]
When completing a task the date of completion is not added, It only prepends a 'x' to the line.

Using the todo.txt cli ```todo.sh do 1```, the completion date is added,

Version: 1.1.3 (Latest from Appcenter)

**Comment by lainsce** [comment]
Since most clients do whatever they want to show completion, I opted for a neutral approach which is the `x` prepended to the line.

**Comment by chrisbeardy** [comment]
That's a shame, would be great to add this, since it adds creation date automatically. Or at least give an option to do so in the preferences. Would you accept a PR for this feature?

**Comment by lainsce** [comment]
I would. Just have to be careful and make the completion format follow the expected type :D
