### ISSUE TITLE
Group by project, and sort by due/creation date

### ISSUE THREAD

**Issue by boramalper** [lainsce/yishu#61]
Hi,

I think it would be amazing if we could group by projects, and sort by due/creation date.

Dates are relatively easier to get done since you can simply add two more columns by which users can order. Projects are harder to handle since each entry can have multiple projects. [SwiftoDo for iOS](https://swiftodoapp.com/) solves this by considering the first project only.

**Comment by boramalper** [comment]
![D4816A74-F809-492C-AB87-F615E6E45841](https://user-images.githubusercontent.com/5618038/103514637-1334b800-4e7e-11eb-9dec-fc70a80022b8.png)

for example

**Comment by lainsce** [comment]
In Yishu Next, I have a sidebar that shows which projects/categories were made, as for sorting dates, it doesn't have that yet.

**Comment by boramalper** [comment]
What is "Yishu Next"?

**Comment by lainsce** [comment]
Check the Pull Requests here in this repository, the pull request there is where Yishu Next is. It's the next version of Yishu.
