### ISSUE TITLE
could you make a flatpak for yishu?

### ISSUE THREAD

**Issue by ghost** [lainsce/yishu#9]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for yishu?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by lainsce** [comment]
I am in the process of making flatpaks for Quilter & Yishu, and the Quilter flatpak is taking all my time in this. 😞

**Comment by ghost** [comment]
i see, i appreciate your work
i hope to see those applications on flatpak format
thanks.

**Comment by lainsce** [comment]
Gonna close this since I'm going to do the flatpak later.
